"""
Generate build metadata for embedding into PyInstaller builds.

This writes `GUI/app/_build_info_generated.py` with values captured from the
current build environment (e.g., distro PRETTY_NAME from /etc/os-release).

Usage:
  python <Pyside6-GUI-Directory>/scripts/generate_build_info.py
  pyinstaller --onefile main.py
"""

from __future__ import annotations

import datetime
import os
import platform
from pathlib import Path


def _read_linux_pretty_name() -> str | None:
    os_release = "/etc/os-release"
    if not os.path.exists(os_release):
        return None
    try:
        with open(os_release, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                if k.strip() == "PRETTY_NAME":
                    return v.strip().strip('"') or None
    except Exception:
        return None
    return None


def _read_windows_pretty_name() -> str | None:
    try:
        release, version, csd, _ptype = platform.win32_ver()
        parts = []
        if release:
            parts.append(f"Windows {release}")
        else:
            parts.append("Windows")
        if version:
            parts.append(f"({version})")
        if csd:
            parts.append(csd)
        return " ".join(parts).strip() or None
    except Exception:
        return None


def _read_macos_pretty_name() -> str | None:
    try:
        release, _versioninfo, _machine = platform.mac_ver()
        if release:
            return f"macOS {release}"
        return "macOS"
    except Exception:
        return None


def _read_pretty_name() -> str:
    # Allow explicit override in CI/build scripts.
    override = os.environ.get("BUILD_DISTRO")
    if override:
        return override

    sysname = platform.system().lower()

    if sysname == "linux":
        return _read_linux_pretty_name() or "Linux"
    if sysname == "windows":
        return _read_windows_pretty_name() or "Windows"
    if sysname == "darwin":
        return _read_macos_pretty_name() or "macOS"

    # Fallback for other OSes
    try:
        return platform.platform() or "unknown"
    except Exception:
        return "unknown"


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    target = repo_root / "GUI" / "app" / "_build_info_generated.py"

    distro = _read_pretty_name()
    now = (
        datetime.datetime.now(datetime.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )

    target.write_text(
        (
            '"""Auto-generated by scripts/generate_build_info.py."""\n\n'
            f'BUILD_DISTRO = {distro!r}\n'
            f'BUILD_TIME_UTC = {now!r}\n'
            "__all__ = ['BUILD_DISTRO', 'BUILD_TIME_UTC']\n"
        ),
        encoding="utf-8",
    )
    print(f"Wrote {target} (BUILD_DISTRO={distro!r}, BUILD_TIME_UTC={now!r})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

